services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - API_KEY_ANT=${API_KEY_ANT}
      - API_KEY_OAI=${API_KEY_OAI}
      - API_KEY_GEM=${API_KEY_GEM}